# Generated by Django 3.0.7 on 2020-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokoUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nama_toko', models.CharField(max_length=255)),
                ('kode_pos', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longtitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
